project_id = "okurngvcodmljjicopdp"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.submit-signature]
verify_jwt = false

[functions.whatsapp-process-scheduled]
verify_jwt = false

[functions.whatsapp-status-worker]
verify_jwt = false

[functions.whatsapp-queue-worker]
verify_jwt = false

[functions.ai-agent]
verify_jwt = true
