-- CONCEDE PERMISSÕES BÁSICAS DE ACESSO PARA USUÁRIOS LOGADOS
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO authenticated;

-- GARANTE QUE O ADMIN ESPECÍFICO TENHA PODER TOTAL (CASO O RLS FALHE)
ALTER TABLE public.app_users FORCE ROW LEVEL SECURITY;
