-- 03 · Chaves estrangeiras (depois de todas as tabelas, para não depender de ordem)
-- Gerado por scripts/snapshot-producao.mjs a partir dos catálogos do banco de produção.
-- NÃO editar à mão: regenerar. A data e as contagens ficam no README.md ao lado.

ALTER TABLE public.agenda_suggestions ADD CONSTRAINT agenda_suggestions_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.agenda_suggestions ADD CONSTRAINT agenda_suggestions_created_task_id_fkey FOREIGN KEY (created_task_id) REFERENCES agenda_tasks(id) ON DELETE SET NULL;
ALTER TABLE public.agenda_suggestions ADD CONSTRAINT agenda_suggestions_open_loop_id_fkey FOREIGN KEY (open_loop_id) REFERENCES entity_open_loops(id) ON DELETE SET NULL;
ALTER TABLE public.agenda_suggestions ADD CONSTRAINT agenda_suggestions_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES app_users(id);
ALTER TABLE public.agenda_suggestions ADD CONSTRAINT agenda_suggestions_source_message_id_fkey FOREIGN KEY (source_message_id) REFERENCES whatsapp_messages(id) ON DELETE SET NULL;
ALTER TABLE public.agenda_suggestions ADD CONSTRAINT agenda_suggestions_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE public.agenda_tasks ADD CONSTRAINT agenda_tasks_assignee_user_id_fkey FOREIGN KEY (assignee_user_id) REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE public.agenda_tasks ADD CONSTRAINT agenda_tasks_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.agenda_tasks ADD CONSTRAINT agenda_tasks_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES app_users(id);
ALTER TABLE public.agenda_tasks ADD CONSTRAINT agenda_tasks_recurrence_parent_id_fkey FOREIGN KEY (recurrence_parent_id) REFERENCES agenda_tasks(id) ON DELETE CASCADE;
ALTER TABLE public.ai_correction_patterns ADD CONSTRAINT ai_correction_patterns_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.ai_inbound_sessions ADD CONSTRAINT ai_inbound_sessions_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.ai_learned_routines ADD CONSTRAINT ai_learned_routines_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES app_users(id);
ALTER TABLE public.ai_learned_routines ADD CONSTRAINT ai_learned_routines_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE public.ai_operator_audit ADD CONSTRAINT ai_operator_audit_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_audit ADD CONSTRAINT ai_operator_audit_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES ai_operator_drafts(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_audit ADD CONSTRAINT ai_operator_audit_pending_action_id_fkey FOREIGN KEY (pending_action_id) REFERENCES ai_operator_pending_actions(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_audit ADD CONSTRAINT ai_operator_audit_session_id_fkey FOREIGN KEY (session_id) REFERENCES ai_operator_sessions(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_channel_events ADD CONSTRAINT ai_operator_channel_events_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES ai_operator_drafts(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_channel_events ADD CONSTRAINT ai_operator_channel_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES ai_operator_sessions(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_draft_items ADD CONSTRAINT ai_operator_draft_items_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES ai_operator_drafts(id) ON DELETE CASCADE;
ALTER TABLE public.ai_operator_draft_items ADD CONSTRAINT ai_operator_draft_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_draft_items ADD CONSTRAINT ai_operator_draft_items_service_id_fkey FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_drafts ADD CONSTRAINT ai_operator_drafts_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_drafts ADD CONSTRAINT ai_operator_drafts_converted_service_order_id_fkey FOREIGN KEY (converted_service_order_id) REFERENCES service_orders(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_drafts ADD CONSTRAINT ai_operator_drafts_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_drafts ADD CONSTRAINT ai_operator_drafts_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_drafts ADD CONSTRAINT ai_operator_drafts_session_id_fkey FOREIGN KEY (session_id) REFERENCES ai_operator_sessions(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_drafts ADD CONSTRAINT ai_operator_drafts_vessel_id_fkey FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_memory_notes ADD CONSTRAINT ai_operator_memory_notes_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public.ai_operator_memory_notes ADD CONSTRAINT ai_operator_memory_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_memory_notes ADD CONSTRAINT ai_operator_memory_notes_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES ai_operator_drafts(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_memory_notes ADD CONSTRAINT ai_operator_memory_notes_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_memory_notes ADD CONSTRAINT ai_operator_memory_notes_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE;
ALTER TABLE public.ai_operator_memory_notes ADD CONSTRAINT ai_operator_memory_notes_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_memory_notes ADD CONSTRAINT ai_operator_memory_notes_vessel_id_fkey FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE CASCADE;
ALTER TABLE public.ai_operator_messages ADD CONSTRAINT ai_operator_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES ai_operator_sessions(id) ON DELETE CASCADE;
ALTER TABLE public.ai_operator_pending_actions ADD CONSTRAINT ai_operator_pending_actions_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_pending_actions ADD CONSTRAINT ai_operator_pending_actions_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES ai_operator_drafts(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_pending_actions ADD CONSTRAINT ai_operator_pending_actions_rejected_by_user_id_fkey FOREIGN KEY (rejected_by_user_id) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_pending_actions ADD CONSTRAINT ai_operator_pending_actions_requested_by_user_id_fkey FOREIGN KEY (requested_by_user_id) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_pending_actions ADD CONSTRAINT ai_operator_pending_actions_session_id_fkey FOREIGN KEY (session_id) REFERENCES ai_operator_sessions(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_sessions ADD CONSTRAINT ai_operator_sessions_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_sessions ADD CONSTRAINT ai_operator_sessions_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_sessions ADD CONSTRAINT ai_operator_sessions_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE SET NULL;
ALTER TABLE public.ai_operator_sessions ADD CONSTRAINT ai_operator_sessions_vessel_id_fkey FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE SET NULL;
ALTER TABLE public.ai_suggestion_reviews ADD CONSTRAINT ai_suggestion_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES app_users(id);
ALTER TABLE public.ai_suggestion_reviews ADD CONSTRAINT ai_suggestion_reviews_service_id_fkey FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL;
ALTER TABLE public.ai_workflows ADD CONSTRAINT ai_workflows_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.app_notifications ADD CONSTRAINT app_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE public.bank_balance_checks ADD CONSTRAINT bank_balance_checks_bank_connection_id_fkey FOREIGN KEY (bank_connection_id) REFERENCES bank_connections(id) ON DELETE CASCADE;
ALTER TABLE public.bank_charges ADD CONSTRAINT bank_charges_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.bank_charges ADD CONSTRAINT bank_charges_receivable_id_fkey FOREIGN KEY (receivable_id) REFERENCES receivables(id) ON DELETE SET NULL;
ALTER TABLE public.bank_charges ADD CONSTRAINT bank_charges_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE SET NULL;
ALTER TABLE public.bank_transactions ADD CONSTRAINT bank_transactions_bank_connection_id_fkey FOREIGN KEY (bank_connection_id) REFERENCES bank_connections(id) ON DELETE SET NULL;
ALTER TABLE public.bank_transactions ADD CONSTRAINT bank_transactions_dismissed_by_fkey FOREIGN KEY (dismissed_by) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.bank_transactions ADD CONSTRAINT bank_transactions_reconciled_payment_id_fkey FOREIGN KEY (reconciled_payment_id) REFERENCES payments(id);
ALTER TABLE public.bank_transactions ADD CONSTRAINT bank_transactions_reconciled_service_order_id_fkey FOREIGN KEY (reconciled_service_order_id) REFERENCES service_orders(id);
ALTER TABLE public.client_whatsapp_settings ADD CONSTRAINT client_whatsapp_settings_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public.collection_contacts ADD CONSTRAINT collection_contacts_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES collections(id) ON DELETE CASCADE;
ALTER TABLE public.collection_contacts ADD CONSTRAINT collection_contacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_users(id);
ALTER TABLE public.collections ADD CONSTRAINT collections_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public.collections ADD CONSTRAINT collections_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_users(id);
ALTER TABLE public.collections ADD CONSTRAINT collections_receivable_id_fkey FOREIGN KEY (receivable_id) REFERENCES receivables(id) ON DELETE SET NULL;
ALTER TABLE public.collections ADD CONSTRAINT collections_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE SET NULL;
ALTER TABLE public.commissions ADD CONSTRAINT commissions_payable_id_fkey FOREIGN KEY (payable_id) REFERENCES payables(id);
ALTER TABLE public.commissions ADD CONSTRAINT commissions_payee_id_fkey FOREIGN KEY (payee_id) REFERENCES payees(id) ON DELETE SET NULL;
ALTER TABLE public.commissions ADD CONSTRAINT commissions_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE CASCADE;
ALTER TABLE public.commissions ADD CONSTRAINT commissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(id);
ALTER TABLE public.cost_centers ADD CONSTRAINT cost_centers_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES cost_centers(id);
ALTER TABLE public.dc_ampacity_ratings ADD CONSTRAINT dc_ampacity_ratings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.entity_open_loops ADD CONSTRAINT entity_open_loops_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE SET NULL;
ALTER TABLE public.entity_open_loops ADD CONSTRAINT entity_open_loops_task_id_fkey FOREIGN KEY (task_id) REFERENCES agenda_tasks(id) ON DELETE SET NULL;
ALTER TABLE public.external_quote_leads ADD CONSTRAINT external_quote_leads_promoted_client_id_fkey FOREIGN KEY (promoted_client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.external_quote_parts ADD CONSTRAINT external_quote_parts_external_quote_id_fkey FOREIGN KEY (external_quote_id) REFERENCES external_quotes(id) ON DELETE CASCADE;
ALTER TABLE public.external_quote_parts ADD CONSTRAINT external_quote_parts_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.external_quote_services ADD CONSTRAINT external_quote_services_external_quote_id_fkey FOREIGN KEY (external_quote_id) REFERENCES external_quotes(id) ON DELETE CASCADE;
ALTER TABLE public.external_quotes ADD CONSTRAINT external_quotes_ai_operator_draft_id_fkey FOREIGN KEY (ai_operator_draft_id) REFERENCES ai_operator_drafts(id) ON DELETE SET NULL;
ALTER TABLE public.external_quotes ADD CONSTRAINT external_quotes_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.external_quotes ADD CONSTRAINT external_quotes_converted_service_order_id_fkey FOREIGN KEY (converted_service_order_id) REFERENCES service_orders(id) ON DELETE SET NULL;
ALTER TABLE public.external_quotes ADD CONSTRAINT external_quotes_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES external_quote_leads(id) ON DELETE SET NULL;
ALTER TABLE public.external_quotes ADD CONSTRAINT external_quotes_marina_id_fkey FOREIGN KEY (marina_id) REFERENCES marinas(id) ON DELETE SET NULL;
ALTER TABLE public.external_quotes ADD CONSTRAINT external_quotes_vessel_id_fkey FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE SET NULL;
ALTER TABLE public.finance_review_queue ADD CONSTRAINT finance_review_queue_applied_rule_id_fkey FOREIGN KEY (applied_rule_id) REFERENCES finance_rules(id) ON DELETE SET NULL;
ALTER TABLE public.finance_review_queue ADD CONSTRAINT finance_review_queue_bank_transaction_id_fkey FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE CASCADE;
ALTER TABLE public.finance_review_queue ADD CONSTRAINT finance_review_queue_created_payable_id_fkey FOREIGN KEY (created_payable_id) REFERENCES payables(id) ON DELETE SET NULL;
ALTER TABLE public.finance_review_queue ADD CONSTRAINT finance_review_queue_created_receivable_id_fkey FOREIGN KEY (created_receivable_id) REFERENCES receivables(id) ON DELETE SET NULL;
ALTER TABLE public.finance_review_queue ADD CONSTRAINT finance_review_queue_related_transaction_id_fkey FOREIGN KEY (related_transaction_id) REFERENCES bank_transactions(id) ON DELETE SET NULL;
ALTER TABLE public.finance_review_queue ADD CONSTRAINT finance_review_queue_suggested_client_id_fkey FOREIGN KEY (suggested_client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.finance_review_queue ADD CONSTRAINT finance_review_queue_suggested_payee_id_fkey FOREIGN KEY (suggested_payee_id) REFERENCES payees(id) ON DELETE SET NULL;
ALTER TABLE public.finance_review_queue ADD CONSTRAINT finance_review_queue_suggested_purchase_order_id_fkey FOREIGN KEY (suggested_purchase_order_id) REFERENCES purchase_orders(id) ON DELETE SET NULL;
ALTER TABLE public.finance_review_queue ADD CONSTRAINT finance_review_queue_suggested_service_order_id_fkey FOREIGN KEY (suggested_service_order_id) REFERENCES service_orders(id) ON DELETE SET NULL;
ALTER TABLE public.finance_review_queue ADD CONSTRAINT finance_review_queue_suggested_supplier_id_fkey FOREIGN KEY (suggested_supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;
ALTER TABLE public.finance_rules ADD CONSTRAINT finance_rules_set_supplier_id_fkey FOREIGN KEY (set_supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;
ALTER TABLE public.fiscal_emission_drafts ADD CONSTRAINT fiscal_emission_drafts_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.fiscal_note_items ADD CONSTRAINT fiscal_note_items_fiscal_note_id_fkey FOREIGN KEY (fiscal_note_id) REFERENCES fiscal_notes(id) ON DELETE CASCADE;
ALTER TABLE public.fiscal_note_items ADD CONSTRAINT fiscal_note_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE public.fiscal_note_items ADD CONSTRAINT fiscal_note_items_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE SET NULL;
ALTER TABLE public.fiscal_notes ADD CONSTRAINT fiscal_notes_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id);
ALTER TABLE public.fiscal_notes ADD CONSTRAINT fiscal_notes_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
ALTER TABLE public.inventory_movements ADD CONSTRAINT inventory_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_users(id) ON DELETE RESTRICT;
ALTER TABLE public.inventory_movements ADD CONSTRAINT inventory_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.inventory_movements ADD CONSTRAINT inventory_movements_reverses_movement_id_fkey FOREIGN KEY (reverses_movement_id) REFERENCES inventory_movements(id);
ALTER TABLE public.invoices ADD CONSTRAINT invoices_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE RESTRICT;
ALTER TABLE public.issued_fiscal_documents ADD CONSTRAINT issued_fiscal_documents_receivable_id_fkey FOREIGN KEY (receivable_id) REFERENCES receivables(id) ON DELETE SET NULL;
ALTER TABLE public.maintenance_plans ADD CONSTRAINT maintenance_plans_vessel_id_fkey FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE CASCADE;
ALTER TABLE public.payables ADD CONSTRAINT payables_bank_transaction_id_fkey FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions(id);
ALTER TABLE public.payables ADD CONSTRAINT payables_cost_center_id_fkey FOREIGN KEY (cost_center_id) REFERENCES cost_centers(id);
ALTER TABLE public.payables ADD CONSTRAINT payables_fiscal_note_id_fkey FOREIGN KEY (fiscal_note_id) REFERENCES fiscal_notes(id);
ALTER TABLE public.payables ADD CONSTRAINT payables_linked_service_order_id_fkey FOREIGN KEY (linked_service_order_id) REFERENCES service_orders(id) ON DELETE RESTRICT;
ALTER TABLE public.payables ADD CONSTRAINT payables_payee_id_fkey FOREIGN KEY (payee_id) REFERENCES payees(id) ON DELETE SET NULL;
ALTER TABLE public.payables ADD CONSTRAINT payables_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
ALTER TABLE public.payees ADD CONSTRAINT payees_app_user_id_fkey FOREIGN KEY (app_user_id) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.payments ADD CONSTRAINT payments_payable_id_fkey FOREIGN KEY (payable_id) REFERENCES payables(id) ON DELETE CASCADE;
ALTER TABLE public.payments ADD CONSTRAINT payments_receivable_id_fkey FOREIGN KEY (receivable_id) REFERENCES receivables(id) ON DELETE CASCADE;
ALTER TABLE public.payroll_lines ADD CONSTRAINT payroll_lines_payable_id_fkey FOREIGN KEY (payable_id) REFERENCES payables(id) ON DELETE SET NULL;
ALTER TABLE public.payroll_lines ADD CONSTRAINT payroll_lines_payroll_period_id_fkey FOREIGN KEY (payroll_period_id) REFERENCES payroll_periods(id) ON DELETE CASCADE;
ALTER TABLE public.payroll_lines ADD CONSTRAINT payroll_lines_work_profile_id_fkey FOREIGN KEY (work_profile_id) REFERENCES work_profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.payroll_periods ADD CONSTRAINT payroll_periods_fechado_por_fkey FOREIGN KEY (fechado_por) REFERENCES app_users(id);
ALTER TABLE public.periodos_fechados ADD CONSTRAINT periodos_fechados_fechado_por_fkey FOREIGN KEY (fechado_por) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.periodos_fechados ADD CONSTRAINT periodos_fechados_reaberto_por_fkey FOREIGN KEY (reaberto_por) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.price_update_suggestions ADD CONSTRAINT price_update_suggestions_fiscal_note_id_fkey FOREIGN KEY (fiscal_note_id) REFERENCES fiscal_notes(id) ON DELETE CASCADE;
ALTER TABLE public.price_update_suggestions ADD CONSTRAINT price_update_suggestions_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.product_aliases ADD CONSTRAINT product_aliases_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.product_components ADD CONSTRAINT product_components_component_product_id_fkey FOREIGN KEY (component_product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.product_components ADD CONSTRAINT product_components_parent_product_id_fkey FOREIGN KEY (parent_product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.product_price_history ADD CONSTRAINT product_price_history_fiscal_note_id_fkey FOREIGN KEY (fiscal_note_id) REFERENCES fiscal_notes(id) ON DELETE SET NULL;
ALTER TABLE public.product_price_history ADD CONSTRAINT product_price_history_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.product_suppliers ADD CONSTRAINT product_suppliers_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.product_suppliers ADD CONSTRAINT product_suppliers_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_product_category_id_fkey FOREIGN KEY (product_category_id) REFERENCES product_categories(id);
ALTER TABLE public.products ADD CONSTRAINT products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
ALTER TABLE public.purchase_order_items ADD CONSTRAINT purchase_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.purchase_order_items ADD CONSTRAINT purchase_order_items_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE;
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_payable_id_fkey FOREIGN KEY (payable_id) REFERENCES payables(id) ON DELETE SET NULL;
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE SET NULL;
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;
ALTER TABLE public.push_subscriptions ADD CONSTRAINT push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE public.quote_request_items ADD CONSTRAINT quote_request_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.quote_request_items ADD CONSTRAINT quote_request_items_quote_request_id_fkey FOREIGN KEY (quote_request_id) REFERENCES quote_requests(id) ON DELETE CASCADE;
ALTER TABLE public.quote_request_items ADD CONSTRAINT quote_request_items_service_order_part_id_fkey FOREIGN KEY (service_order_part_id) REFERENCES service_order_parts(id) ON DELETE SET NULL;
ALTER TABLE public.quote_request_items ADD CONSTRAINT quote_request_items_service_order_service_id_fkey FOREIGN KEY (service_order_service_id) REFERENCES service_order_services(id) ON DELETE SET NULL;
ALTER TABLE public.quote_request_sends ADD CONSTRAINT quote_request_sends_queue_id_fkey FOREIGN KEY (queue_id) REFERENCES whatsapp_send_queue(id) ON DELETE SET NULL;
ALTER TABLE public.quote_request_sends ADD CONSTRAINT quote_request_sends_quote_request_id_fkey FOREIGN KEY (quote_request_id) REFERENCES quote_requests(id) ON DELETE CASCADE;
ALTER TABLE public.quote_request_sends ADD CONSTRAINT quote_request_sends_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
ALTER TABLE public.quote_requests ADD CONSTRAINT quote_requests_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE SET NULL;
ALTER TABLE public.quote_responses ADD CONSTRAINT quote_responses_quote_request_id_fkey FOREIGN KEY (quote_request_id) REFERENCES quote_requests(id) ON DELETE CASCADE;
ALTER TABLE public.quote_responses ADD CONSTRAINT quote_responses_quote_request_item_id_fkey FOREIGN KEY (quote_request_item_id) REFERENCES quote_request_items(id) ON DELETE CASCADE;
ALTER TABLE public.quote_responses ADD CONSTRAINT quote_responses_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE;
ALTER TABLE public.receivables ADD CONSTRAINT receivables_bank_transaction_id_fkey FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE SET NULL;
ALTER TABLE public.receivables ADD CONSTRAINT receivables_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT;
ALTER TABLE public.receivables ADD CONSTRAINT receivables_cost_center_id_fkey FOREIGN KEY (cost_center_id) REFERENCES cost_centers(id);
ALTER TABLE public.receivables ADD CONSTRAINT receivables_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE RESTRICT;
ALTER TABLE public.receivables ADD CONSTRAINT receivables_issued_fiscal_document_id_fkey FOREIGN KEY (issued_fiscal_document_id) REFERENCES issued_fiscal_documents(id) ON DELETE SET NULL;
ALTER TABLE public.receivables ADD CONSTRAINT receivables_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE RESTRICT;
ALTER TABLE public.reconciliation_log ADD CONSTRAINT reconciliation_log_autor_fkey FOREIGN KEY (autor) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.reconciliation_log ADD CONSTRAINT reconciliation_log_bank_transaction_id_fkey FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE SET NULL;
ALTER TABLE public.reconciliation_log ADD CONSTRAINT reconciliation_log_finance_rule_id_fkey FOREIGN KEY (finance_rule_id) REFERENCES finance_rules(id) ON DELETE SET NULL;
ALTER TABLE public.reconciliation_log ADD CONSTRAINT reconciliation_log_payable_id_fkey FOREIGN KEY (payable_id) REFERENCES payables(id) ON DELETE SET NULL;
ALTER TABLE public.reconciliation_log ADD CONSTRAINT reconciliation_log_receivable_id_fkey FOREIGN KEY (receivable_id) REFERENCES receivables(id) ON DELETE SET NULL;
ALTER TABLE public.reconciliation_memory ADD CONSTRAINT reconciliation_memory_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public.service_cases ADD CONSTRAINT service_cases_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.service_cases ADD CONSTRAINT service_cases_marina_id_fkey FOREIGN KEY (marina_id) REFERENCES marinas(id) ON DELETE SET NULL;
ALTER TABLE public.service_cases ADD CONSTRAINT service_cases_service_id_fkey FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL;
ALTER TABLE public.service_cases ADD CONSTRAINT service_cases_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE CASCADE;
ALTER TABLE public.service_cases ADD CONSTRAINT service_cases_vessel_id_fkey FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE SET NULL;
ALTER TABLE public.service_fiscal_verbs ADD CONSTRAINT service_fiscal_verbs_verb_slug_fkey FOREIGN KEY (verb_slug) REFERENCES service_verbs(slug) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.service_order_expenses ADD CONSTRAINT service_order_expenses_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_users(id);
ALTER TABLE public.service_order_expenses ADD CONSTRAINT service_order_expenses_linked_payable_id_fkey FOREIGN KEY (linked_payable_id) REFERENCES payables(id);
ALTER TABLE public.service_order_expenses ADD CONSTRAINT service_order_expenses_reimbursed_payment_id_fkey FOREIGN KEY (reimbursed_payment_id) REFERENCES payments(id);
ALTER TABLE public.service_order_expenses ADD CONSTRAINT service_order_expenses_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE CASCADE;
ALTER TABLE public.service_order_expenses ADD CONSTRAINT service_order_expenses_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;
ALTER TABLE public.service_order_expenses ADD CONSTRAINT service_order_expenses_technician_user_id_fkey FOREIGN KEY (technician_user_id) REFERENCES app_users(id);
ALTER TABLE public.service_order_parts ADD CONSTRAINT service_order_parts_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.service_order_parts ADD CONSTRAINT service_order_parts_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE CASCADE;
ALTER TABLE public.service_order_parts ADD CONSTRAINT service_order_parts_service_order_service_id_fkey FOREIGN KEY (service_order_service_id) REFERENCES service_order_services(id) ON DELETE SET NULL;
ALTER TABLE public.service_order_photos ADD CONSTRAINT service_order_photos_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE CASCADE;
ALTER TABLE public.service_order_photos ADD CONSTRAINT service_order_photos_step_id_fkey FOREIGN KEY (step_id) REFERENCES service_order_steps(id) ON DELETE SET NULL;
ALTER TABLE public.service_order_photos ADD CONSTRAINT service_order_photos_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES app_users(id);
ALTER TABLE public.service_order_services ADD CONSTRAINT service_order_services_service_id_fkey FOREIGN KEY (service_id) REFERENCES services(id);
ALTER TABLE public.service_order_services ADD CONSTRAINT service_order_services_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE CASCADE;
ALTER TABLE public.service_order_services ADD CONSTRAINT service_order_services_service_system_fkey FOREIGN KEY (service_system) REFERENCES service_systems(slug) ON UPDATE CASCADE;
ALTER TABLE public.service_order_services ADD CONSTRAINT service_order_services_service_verb_fkey FOREIGN KEY (service_verb) REFERENCES service_verbs(slug) ON UPDATE CASCADE;
ALTER TABLE public.service_order_services ADD CONSTRAINT sos_fiscal_verb_fk FOREIGN KEY (fiscal_verb) REFERENCES service_fiscal_verbs(verb_slug) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.service_order_signatures ADD CONSTRAINT service_order_signatures_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE CASCADE;
ALTER TABLE public.service_order_steps ADD CONSTRAINT service_order_steps_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES app_users(id);
ALTER TABLE public.service_order_steps ADD CONSTRAINT service_order_steps_assigned_user_id_fkey FOREIGN KEY (assigned_user_id) REFERENCES app_users(id);
ALTER TABLE public.service_order_steps ADD CONSTRAINT service_order_steps_blocked_reason_code_fkey FOREIGN KEY (blocked_reason_code) REFERENCES work_stop_reasons(code);
ALTER TABLE public.service_order_steps ADD CONSTRAINT service_order_steps_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE CASCADE;
ALTER TABLE public.service_order_steps ADD CONSTRAINT service_order_steps_service_order_service_id_fkey FOREIGN KEY (service_order_service_id) REFERENCES service_order_services(id) ON DELETE SET NULL;
ALTER TABLE public.service_order_steps ADD CONSTRAINT service_order_steps_template_id_fkey FOREIGN KEY (template_id) REFERENCES service_step_templates(id) ON DELETE SET NULL;
ALTER TABLE public.service_order_technicians ADD CONSTRAINT service_order_technicians_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE CASCADE;
ALTER TABLE public.service_order_technicians ADD CONSTRAINT service_order_technicians_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE RESTRICT;
ALTER TABLE public.service_orders ADD CONSTRAINT service_orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT;
ALTER TABLE public.service_orders ADD CONSTRAINT service_orders_commissioned_user_id_fkey FOREIGN KEY (commissioned_user_id) REFERENCES app_users(id);
ALTER TABLE public.service_orders ADD CONSTRAINT service_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_users(id) ON DELETE RESTRICT;
ALTER TABLE public.service_orders ADD CONSTRAINT service_orders_marina_id_fkey FOREIGN KEY (marina_id) REFERENCES marinas(id) ON DELETE RESTRICT;
ALTER TABLE public.service_orders ADD CONSTRAINT service_orders_payment_condition_preset_id_fkey FOREIGN KEY (payment_condition_preset_id) REFERENCES payment_condition_presets(id) ON DELETE SET NULL;
ALTER TABLE public.service_orders ADD CONSTRAINT service_orders_requested_by_contact_id_fkey FOREIGN KEY (requested_by_contact_id) REFERENCES vessel_contacts(id);
ALTER TABLE public.service_orders ADD CONSTRAINT service_orders_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES service_surveys(id) ON DELETE SET NULL;
ALTER TABLE public.service_orders ADD CONSTRAINT service_orders_vessel_id_fkey FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE RESTRICT;
ALTER TABLE public.service_step_blocks ADD CONSTRAINT service_step_blocks_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES app_users(id);
ALTER TABLE public.service_step_blocks ADD CONSTRAINT step_blocks_system_fk FOREIGN KEY (applies_to_system) REFERENCES service_systems(slug) ON UPDATE CASCADE;
ALTER TABLE public.service_step_blocks ADD CONSTRAINT step_blocks_verb_fk FOREIGN KEY (applies_to_verb) REFERENCES service_verbs(slug) ON UPDATE CASCADE;
ALTER TABLE public.service_step_templates ADD CONSTRAINT service_step_templates_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES app_users(id);
ALTER TABLE public.service_step_templates ADD CONSTRAINT service_step_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_users(id);
ALTER TABLE public.service_step_templates ADD CONSTRAINT service_step_templates_service_id_fkey FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE;
ALTER TABLE public.service_survey_answers ADD CONSTRAINT service_survey_answers_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES service_surveys(id) ON DELETE CASCADE;
ALTER TABLE public.service_survey_answers ADD CONSTRAINT service_survey_answers_template_id_fkey FOREIGN KEY (template_id) REFERENCES service_survey_templates(id) ON DELETE SET NULL;
ALTER TABLE public.service_survey_templates ADD CONSTRAINT service_survey_templates_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES app_users(id);
ALTER TABLE public.service_survey_templates ADD CONSTRAINT service_survey_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_users(id);
ALTER TABLE public.service_survey_templates ADD CONSTRAINT service_survey_templates_service_id_fkey FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE;
ALTER TABLE public.service_survey_templates ADD CONSTRAINT survey_tpl_system_fk FOREIGN KEY (applies_to_system) REFERENCES service_systems(slug) ON UPDATE CASCADE;
ALTER TABLE public.service_survey_templates ADD CONSTRAINT survey_tpl_verb_fk FOREIGN KEY (applies_to_verb) REFERENCES service_verbs(slug) ON UPDATE CASCADE;
ALTER TABLE public.service_surveys ADD CONSTRAINT service_surveys_answered_by_fkey FOREIGN KEY (answered_by) REFERENCES app_users(id);
ALTER TABLE public.service_surveys ADD CONSTRAINT service_surveys_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.service_surveys ADD CONSTRAINT service_surveys_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_users(id);
ALTER TABLE public.service_surveys ADD CONSTRAINT service_surveys_service_id_fkey FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL;
ALTER TABLE public.service_surveys ADD CONSTRAINT service_surveys_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE CASCADE;
ALTER TABLE public.service_surveys ADD CONSTRAINT service_surveys_vessel_id_fkey FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE SET NULL;
ALTER TABLE public.services ADD CONSTRAINT services_fiscal_verb_fk FOREIGN KEY (fiscal_verb) REFERENCES service_fiscal_verbs(verb_slug) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.services ADD CONSTRAINT services_material_kit_product_id_fkey FOREIGN KEY (material_kit_product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE public.services ADD CONSTRAINT services_system_fk FOREIGN KEY (service_system) REFERENCES service_systems(slug) ON UPDATE CASCADE;
ALTER TABLE public.services ADD CONSTRAINT services_verb_fk FOREIGN KEY (service_verb) REFERENCES service_verbs(slug) ON UPDATE CASCADE;
ALTER TABLE public.supplier_product_mappings ADD CONSTRAINT supplier_product_mappings_internal_product_id_fkey FOREIGN KEY (internal_product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE public.supplier_product_mappings ADD CONSTRAINT supplier_product_mappings_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE;
ALTER TABLE public.survey_material_rules ADD CONSTRAINT survey_material_rules_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id);
ALTER TABLE public.survey_material_rules ADD CONSTRAINT survey_material_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.survey_material_rules ADD CONSTRAINT survey_material_rules_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT;
ALTER TABLE public.survey_material_rules ADD CONSTRAINT survey_material_rules_template_id_fkey FOREIGN KEY (template_id) REFERENCES service_survey_templates(id) ON DELETE CASCADE;
ALTER TABLE public.task_reminders ADD CONSTRAINT task_reminders_task_id_fkey FOREIGN KEY (task_id) REFERENCES agenda_tasks(id) ON DELETE CASCADE;
ALTER TABLE public.time_entries ADD CONSTRAINT time_entries_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE CASCADE;
ALTER TABLE public.time_entries ADD CONSTRAINT time_entries_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES work_shifts(id) ON DELETE SET NULL;
ALTER TABLE public.time_entries ADD CONSTRAINT time_entries_step_id_fkey FOREIGN KEY (step_id) REFERENCES service_order_steps(id) ON DELETE SET NULL;
ALTER TABLE public.time_entries ADD CONSTRAINT time_entries_stop_reason_code_fkey FOREIGN KEY (stop_reason_code) REFERENCES work_stop_reasons(code);
ALTER TABLE public.time_entries ADD CONSTRAINT time_entries_technician_user_id_fkey FOREIGN KEY (technician_user_id) REFERENCES app_users(id) ON DELETE RESTRICT;
ALTER TABLE public.vessel_contacts ADD CONSTRAINT vessel_contacts_vessel_id_fkey FOREIGN KEY (vessel_id) REFERENCES vessels(id) ON DELETE CASCADE;
ALTER TABLE public.vessels ADD CONSTRAINT vessels_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT;
ALTER TABLE public.vessels ADD CONSTRAINT vessels_marina_id_fkey FOREIGN KEY (marina_id) REFERENCES marinas(id) ON DELETE RESTRICT;
ALTER TABLE public.whatsapp_leads ADD CONSTRAINT whatsapp_leads_linked_client_id_fkey FOREIGN KEY (linked_client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.whatsapp_messages ADD CONSTRAINT whatsapp_messages_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.whatsapp_messages ADD CONSTRAINT whatsapp_messages_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES whatsapp_leads(id) ON DELETE SET NULL;
ALTER TABLE public.whatsapp_messages ADD CONSTRAINT whatsapp_messages_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE SET NULL;
ALTER TABLE public.whatsapp_messages ADD CONSTRAINT whatsapp_messages_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;
ALTER TABLE public.whatsapp_scheduled_sends ADD CONSTRAINT whatsapp_scheduled_sends_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public.whatsapp_scheduled_sends ADD CONSTRAINT whatsapp_scheduled_sends_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.whatsapp_scheduled_sends ADD CONSTRAINT whatsapp_scheduled_sends_receivable_id_fkey FOREIGN KEY (receivable_id) REFERENCES receivables(id) ON DELETE CASCADE;
ALTER TABLE public.whatsapp_scheduled_sends ADD CONSTRAINT whatsapp_scheduled_sends_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE CASCADE;
ALTER TABLE public.whatsapp_status_scheduled ADD CONSTRAINT whatsapp_status_scheduled_created_by_fkey FOREIGN KEY (created_by) REFERENCES app_users(id) ON DELETE SET NULL;
ALTER TABLE public.work_profiles ADD CONSTRAINT work_profiles_app_user_id_fkey FOREIGN KEY (app_user_id) REFERENCES app_users(id) ON DELETE CASCADE;
ALTER TABLE public.work_profiles ADD CONSTRAINT work_profiles_payee_id_fkey FOREIGN KEY (payee_id) REFERENCES payees(id) ON DELETE CASCADE;
ALTER TABLE public.work_shifts ADD CONSTRAINT work_shifts_aprovado_por_fkey FOREIGN KEY (aprovado_por) REFERENCES app_users(id);
ALTER TABLE public.work_shifts ADD CONSTRAINT work_shifts_registrado_por_fkey FOREIGN KEY (registrado_por) REFERENCES app_users(id);
ALTER TABLE public.work_shifts ADD CONSTRAINT work_shifts_service_order_id_fkey FOREIGN KEY (service_order_id) REFERENCES service_orders(id) ON DELETE SET NULL;
ALTER TABLE public.work_shifts ADD CONSTRAINT work_shifts_work_profile_id_fkey FOREIGN KEY (work_profile_id) REFERENCES work_profiles(id) ON DELETE RESTRICT;
