-- 04 · Índices que não sustentam constraint (PK/UNIQUE estão no arquivo 02)
-- Gerado por scripts/snapshot-producao.mjs a partir dos catálogos do banco de produção.
-- NÃO editar à mão: regenerar. A data e as contagens ficam no README.md ao lado.

CREATE UNIQUE INDEX agenda_suggestions_dedupe ON public.agenda_suggestions USING btree (source_message_id, md5(title)) WHERE ((source_message_id IS NOT NULL) AND (status = 'pending'::text));
CREATE INDEX agenda_suggestions_detector_stats ON public.agenda_suggestions USING btree (detector, status);
CREATE INDEX agenda_suggestions_open_loop ON public.agenda_suggestions USING btree (open_loop_id) WHERE (open_loop_id IS NOT NULL);
CREATE INDEX agenda_suggestions_pending ON public.agenda_suggestions USING btree (target_user_id, created_at DESC) WHERE (status = 'pending'::text);
CREATE INDEX agenda_tasks_assignee_due ON public.agenda_tasks USING btree (assignee_user_id, due_at) WHERE (status = ANY (ARRAY['pending'::text, 'in_progress'::text]));
CREATE UNIQUE INDEX agenda_tasks_automation_key_live ON public.agenda_tasks USING btree (automation_key) WHERE ((automation_key IS NOT NULL) AND (status = ANY (ARRAY['pending'::text, 'in_progress'::text])));
CREATE INDEX agenda_tasks_entity ON public.agenda_tasks USING btree (related_entity_type, related_entity_id) WHERE (related_entity_id IS NOT NULL);
CREATE INDEX agenda_tasks_start ON public.agenda_tasks USING btree (scheduled_start_at) WHERE (scheduled_start_at IS NOT NULL);
CREATE INDEX agenda_tasks_start_idx ON public.agenda_tasks USING btree (scheduled_start_at);
CREATE INDEX agenda_tasks_tech_start_idx ON public.agenda_tasks USING btree (assignee_user_id, scheduled_start_at);
CREATE INDEX ai_agent_memory_entity_idx ON public.ai_agent_memory USING btree (entity_id) WHERE (entity_id IS NOT NULL);
CREATE INDEX ai_agent_memory_scope_idx ON public.ai_agent_memory USING btree (scope, memory_key);
CREATE INDEX ai_agent_tasks_due_idx ON public.ai_agent_tasks USING btree (due_at, status) WHERE (status = 'pending'::text);
CREATE INDEX ai_agent_tasks_entity_idx ON public.ai_agent_tasks USING btree (entity_id) WHERE (entity_id IS NOT NULL);
CREATE INDEX ai_business_alerts_active_idx ON public.ai_business_alerts USING btree (severity, last_seen_at DESC) WHERE (resolved_at IS NULL);
CREATE INDEX ai_business_alerts_entity_idx ON public.ai_business_alerts USING btree (entity_id) WHERE (resolved_at IS NULL);
CREATE INDEX idx_ai_comms_log_created ON public.ai_comms_log USING btree (created_at DESC);
CREATE INDEX idx_ai_comms_log_entity ON public.ai_comms_log USING btree (entity_kind, entity_id, tipo, created_at DESC);
CREATE INDEX ai_correction_patterns_client_idx ON public.ai_correction_patterns USING btree (client_id) WHERE (client_id IS NOT NULL);
CREATE INDEX ai_correction_patterns_type_idx ON public.ai_correction_patterns USING btree (correction_type, scope);
CREATE INDEX ai_inbound_sessions_client_idx ON public.ai_inbound_sessions USING btree (client_id) WHERE (client_id IS NOT NULL);
CREATE UNIQUE INDEX ai_learned_routines_key ON public.ai_learned_routines USING btree (pattern_key, COALESCE(user_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX ai_learned_routines_status ON public.ai_learned_routines USING btree (status, observations DESC);
CREATE INDEX ai_lifecycle_events_entity_idx ON public.ai_lifecycle_events USING btree (entity_id, created_at DESC);
CREATE INDEX idx_ai_message_feedback_created ON public.ai_message_feedback USING btree (created_at DESC);
CREATE INDEX idx_ai_alerts_log_created ON public.ai_operator_alerts_log USING btree (created_at DESC);
CREATE UNIQUE INDEX ux_ai_alerts_log_key ON public.ai_operator_alerts_log USING btree (alert_key);
CREATE INDEX idx_ai_op_audit_event ON public.ai_operator_audit USING btree (event_type, created_at);
CREATE INDEX idx_ai_op_audit_session ON public.ai_operator_audit USING btree (session_id, created_at);
CREATE INDEX idx_ai_op_channel_events_status ON public.ai_operator_channel_events USING btree (status, created_at);
CREATE INDEX idx_ai_op_channel_events_thread ON public.ai_operator_channel_events USING btree (external_thread_key);
CREATE UNIQUE INDEX ux_ai_op_channel_events_external ON public.ai_operator_channel_events USING btree (provider, external_event_id) WHERE (external_event_id IS NOT NULL);
CREATE INDEX idx_ai_op_draft_items_draft ON public.ai_operator_draft_items USING btree (draft_id, "position");
CREATE INDEX idx_ai_op_drafts_client ON public.ai_operator_drafts USING btree (client_id);
CREATE INDEX idx_ai_op_drafts_session ON public.ai_operator_drafts USING btree (session_id);
CREATE INDEX idx_ai_op_drafts_status ON public.ai_operator_drafts USING btree (status, kind);
CREATE INDEX idx_ai_op_drafts_vessel ON public.ai_operator_drafts USING btree (vessel_id);
CREATE INDEX idx_ai_op_memory_client ON public.ai_operator_memory_notes USING btree (client_id) WHERE (client_id IS NOT NULL);
CREATE INDEX idx_ai_op_memory_topic ON public.ai_operator_memory_notes USING btree (topic);
CREATE INDEX idx_ai_op_memory_verified ON public.ai_operator_memory_notes USING btree (verification_status);
CREATE INDEX idx_ai_op_memory_vessel ON public.ai_operator_memory_notes USING btree (vessel_id) WHERE (vessel_id IS NOT NULL);
CREATE INDEX idx_memnotes_client_verified ON public.ai_operator_memory_notes USING btree (client_id, verification_status) WHERE (client_id IS NOT NULL);
CREATE INDEX idx_memnotes_supplier ON public.ai_operator_memory_notes USING btree (supplier_id) WHERE (supplier_id IS NOT NULL);
CREATE INDEX idx_ai_msgs_reconcile_pendente ON public.ai_operator_messages USING btree (created_at DESC) WHERE ((openrouter_generation_id IS NOT NULL) AND (custo_reconciliado_em IS NULL) AND (reconcile_tentativas < 5));
CREATE INDEX idx_ai_op_messages_session ON public.ai_operator_messages USING btree (session_id, created_at);
CREATE INDEX idx_ai_op_messages_source ON public.ai_operator_messages USING btree (source_message_id) WHERE (source_message_id IS NOT NULL);
CREATE INDEX idx_ai_op_pending_draft ON public.ai_operator_pending_actions USING btree (draft_id);
CREATE INDEX idx_ai_op_pending_session ON public.ai_operator_pending_actions USING btree (session_id);
CREATE INDEX idx_ai_op_pending_status ON public.ai_operator_pending_actions USING btree (status, created_at);
CREATE INDEX idx_ai_op_pending_status_expires ON public.ai_operator_pending_actions USING btree (status, expires_at);
CREATE INDEX idx_ai_op_sessions_channel ON public.ai_operator_sessions USING btree (channel, status);
CREATE INDEX idx_ai_op_sessions_client ON public.ai_operator_sessions USING btree (client_id);
CREATE INDEX idx_ai_op_sessions_owner ON public.ai_operator_sessions USING btree (owner_user_id);
CREATE INDEX idx_ai_op_sessions_owner_activity ON public.ai_operator_sessions USING btree (owner_user_id, last_activity_at DESC);
CREATE INDEX idx_ai_op_sessions_thread ON public.ai_operator_sessions USING btree (external_thread_key) WHERE (external_thread_key IS NOT NULL);
CREATE INDEX idx_ai_op_sessions_vessel ON public.ai_operator_sessions USING btree (vessel_id);
CREATE INDEX ai_suggestion_reviews_type ON public.ai_suggestion_reviews USING btree (suggestion_type, verdict, reviewed_at DESC);
CREATE INDEX ai_workflows_active_idx ON public.ai_workflows USING btree (status, next_action_at) WHERE (status = 'active'::text);
CREATE INDEX ai_workflows_client_idx ON public.ai_workflows USING btree (client_id) WHERE (client_id IS NOT NULL);
CREATE INDEX ai_workflows_entity_idx ON public.ai_workflows USING btree (entity_id);
CREATE INDEX idx_app_error_logs_recent ON public.app_error_logs USING btree (last_seen_at DESC);
CREATE UNIQUE INDEX uq_app_error_logs_open ON public.app_error_logs USING btree (fingerprint) WHERE (resolved_at IS NULL);
CREATE INDEX app_notifications_user_unread ON public.app_notifications USING btree (user_id, created_at DESC) WHERE (read_at IS NULL);
CREATE INDEX idx_app_users_ai_whatsapp_enabled ON public.app_users USING btree (phone_normalized) WHERE (ai_whatsapp_enabled = true);
CREATE UNIQUE INDEX ux_app_users_phone_normalized ON public.app_users USING btree (phone_normalized) WHERE (phone_normalized IS NOT NULL);
CREATE INDEX idx_balance_checks_conexao ON public.bank_balance_checks USING btree (bank_connection_id, conferido_em DESC);
CREATE UNIQUE INDEX bank_charges_provider_ref ON public.bank_charges USING btree (provider, provider_charge_id) WHERE (provider_charge_id IS NOT NULL);
CREATE INDEX idx_bank_charges_abertas ON public.bank_charges USING btree (status, due_date) WHERE (status = ANY (ARRAY['pending'::text, 'registered'::text, 'overdue'::text]));
CREATE INDEX idx_bank_charges_pix_e2e ON public.bank_charges USING btree (pix_end_to_end_id) WHERE (pix_end_to_end_id IS NOT NULL);
CREATE INDEX idx_bank_charges_receivable ON public.bank_charges USING btree (receivable_id);
CREATE UNIQUE INDEX bank_connections_provider_external ON public.bank_connections USING btree (provider, external_id);
CREATE UNIQUE INDEX bank_transactions_bank_ref_unique ON public.bank_transactions USING btree (bank_ref_id, source_type);
CREATE INDEX idx_bank_transactions_connection ON public.bank_transactions USING btree (bank_connection_id);
CREATE INDEX idx_bank_transactions_ignoradas ON public.bank_transactions USING btree (dismissed_kind, transaction_date DESC) WHERE (dismissed_reason IS NOT NULL);
CREATE INDEX idx_bank_transactions_mcc ON public.bank_transactions USING btree (payee_mcc) WHERE (payee_mcc IS NOT NULL);
CREATE INDEX idx_bank_transactions_pendentes ON public.bank_transactions USING btree (reconciled, transaction_date DESC);
CREATE INDEX idx_bank_transactions_pix_e2e ON public.bank_transactions USING btree (pix_end_to_end_id) WHERE (pix_end_to_end_id IS NOT NULL);
CREATE INDEX idx_client_whatsapp_settings_client ON public.client_whatsapp_settings USING btree (client_id);
CREATE INDEX clients_phone_key8 ON public.clients USING btree ("right"(regexp_replace(COALESCE(phone, ''::text), '\D'::text, ''::text, 'g'::text), 8));
CREATE INDEX clients_whatsapp_key8 ON public.clients USING btree ("right"(regexp_replace(COALESCE(whatsapp, ''::text), '\D'::text, ''::text, 'g'::text), 8));
CREATE INDEX idx_collection_contacts_coll ON public.collection_contacts USING btree (collection_id, created_at DESC);
CREATE INDEX idx_collections_client ON public.collections USING btree (client_id);
CREATE INDEX idx_collections_due_date ON public.collections USING btree (due_date);
CREATE INDEX idx_collections_so ON public.collections USING btree (service_order_id);
CREATE INDEX idx_collections_status ON public.collections USING btree (status);
CREATE UNIQUE INDEX entity_open_loops_alive ON public.entity_open_loops USING btree (entity_type, entity_id, loop_key) WHERE (status = 'open'::text);
CREATE INDEX entity_open_loops_dependem_de_nos_idx ON public.entity_open_loops USING btree (direction, status, due_at, opened_at) WHERE (status = 'open'::text);
CREATE INDEX entity_open_loops_entity ON public.entity_open_loops USING btree (entity_type, entity_id, status, due_at);
CREATE INDEX entity_open_loops_so ON public.entity_open_loops USING btree (service_order_id) WHERE (service_order_id IS NOT NULL);
CREATE INDEX idx_exchange_rates_currencies ON public.exchange_rates USING btree (from_currency, to_currency, recorded_at);
CREATE INDEX leads_phone_key8 ON public.external_quote_leads USING btree ("right"(regexp_replace(COALESCE(phone, ''::text), '\D'::text, ''::text, 'g'::text), 8));
CREATE UNIQUE INDEX external_quotes_ai_operator_draft_id_uidx ON public.external_quotes USING btree (ai_operator_draft_id) WHERE (ai_operator_draft_id IS NOT NULL);
CREATE INDEX idx_eq_created_by ON public.external_quotes USING btree (created_by);
CREATE INDEX idx_eq_status ON public.external_quotes USING btree (status);
CREATE UNIQUE INDEX finance_review_uma_por_transacao ON public.finance_review_queue USING btree (bank_transaction_id, kind) WHERE (status = 'pending'::text);
CREATE INDEX idx_finance_review_fila ON public.finance_review_queue USING btree (status, confidence DESC, created_at);
CREATE UNIQUE INDEX finance_rules_uma_por_alvo ON public.finance_rules USING btree (match_type, lower(match_value), direction) WHERE (status = ANY (ARRAY['active'::text, 'proposed'::text]));
CREATE INDEX idx_finance_rules_ativas ON public.finance_rules USING btree (status, match_type);
CREATE UNIQUE INDEX financial_categories_nome_tipo ON public.financial_categories USING btree (name, type);
CREATE INDEX idx_fed_status_updated ON public.fiscal_emission_drafts USING btree (status, updated_at DESC);
CREATE INDEX idx_fiscal_note_items_matched_product ON public.fiscal_note_items USING btree (matched_product_id);
CREATE INDEX idx_fiscal_note_items_note ON public.fiscal_note_items USING btree (fiscal_note_id);
CREATE INDEX idx_fni_service_order ON public.fiscal_note_items USING btree (service_order_id) WHERE (service_order_id IS NOT NULL);
CREATE INDEX idx_fiscal_notes_issued_at ON public.fiscal_notes USING btree (issued_at DESC);
CREATE INDEX idx_fiscal_notes_nfe_key ON public.fiscal_notes USING btree (nfe_key);
CREATE INDEX idx_fiscal_notes_status ON public.fiscal_notes USING btree (status);
CREATE INDEX idx_inv_mov_reference ON public.inventory_movements USING btree (reference_type, reference_id);
CREATE INDEX idx_inv_movements_product_date ON public.inventory_movements USING btree (product_id, created_at DESC);
CREATE INDEX idx_inventory_movements_product_id ON public.inventory_movements USING btree (product_id);
CREATE UNIQUE INDEX ux_inventory_movements_reverses ON public.inventory_movements USING btree (reverses_movement_id) WHERE (reverses_movement_id IS NOT NULL);
CREATE INDEX idx_invoices_client_id ON public.invoices USING btree (client_id);
CREATE INDEX idx_invoices_so_id ON public.invoices USING btree (service_order_id);
CREATE INDEX idx_ifd_access_key ON public.issued_fiscal_documents USING btree (access_key);
CREATE INDEX idx_ifd_created_at ON public.issued_fiscal_documents USING btree (created_at DESC);
CREATE INDEX idx_ifd_origin ON public.issued_fiscal_documents USING btree (origin_type, origin_id);
CREATE INDEX idx_ifd_provider_doc ON public.issued_fiscal_documents USING btree (provider_document_id);
CREATE INDEX idx_ifd_status ON public.issued_fiscal_documents USING btree (status);
CREATE UNIQUE INDEX uq_ifd_active_per_origin ON public.issued_fiscal_documents USING btree (origin_type, origin_id, document_type) WHERE ((origin_id IS NOT NULL) AND (status = ANY (ARRAY['draft'::text, 'queued'::text, 'processing'::text, 'authorized'::text])));
CREATE UNIQUE INDEX uq_ifd_idempotency_key ON public.issued_fiscal_documents USING btree (idempotency_key) WHERE ((idempotency_key IS NOT NULL) AND (status = ANY (ARRAY['draft'::text, 'queued'::text, 'processing'::text, 'authorized'::text])));
CREATE INDEX maintenance_plans_active ON public.maintenance_plans USING btree (active) WHERE active;
CREATE INDEX maintenance_plans_vessel ON public.maintenance_plans USING btree (vessel_id);
CREATE INDEX idx_payables_fiscal_note ON public.payables USING btree (fiscal_note_id) WHERE (fiscal_note_id IS NOT NULL);
CREATE INDEX idx_payables_linked_so_id ON public.payables USING btree (linked_service_order_id);
CREATE INDEX idx_payables_payee ON public.payables USING btree (payee_id) WHERE (payee_id IS NOT NULL);
CREATE INDEX idx_payables_supplier_status ON public.payables USING btree (supplier_id, status);
CREATE UNIQUE INDEX payables_uma_por_transacao ON public.payables USING btree (bank_transaction_id) WHERE (bank_transaction_id IS NOT NULL);
CREATE INDEX idx_payees_ativos ON public.payees USING btree (active, kind, name);
CREATE UNIQUE INDEX payees_documento_unico ON public.payees USING btree (document) WHERE ((document IS NOT NULL) AND (document <> ''::text));
CREATE INDEX payees_por_app_user ON public.payees USING btree (app_user_id) WHERE (app_user_id IS NOT NULL);
CREATE UNIQUE INDEX payees_um_app_user ON public.payees USING btree (app_user_id) WHERE (app_user_id IS NOT NULL);
CREATE INDEX idx_payments_date ON public.payments USING btree (payment_date DESC);
CREATE INDEX payroll_lines_por_periodo ON public.payroll_lines USING btree (payroll_period_id);
CREATE UNIQUE INDEX payroll_periods_intervalo_unico ON public.payroll_periods USING btree (de, ate);
CREATE UNIQUE INDEX pluggy_amostra_unica ON public.pluggy_amostra_payload USING btree (bank_ref_id);
CREATE INDEX idx_product_aliases_product ON public.product_aliases USING btree (product_id);
CREATE INDEX idx_product_components_component ON public.product_components USING btree (component_product_id);
CREATE INDEX idx_product_components_parent ON public.product_components USING btree (parent_product_id);
CREATE INDEX idx_products_barcode ON public.products USING btree (barcode) WHERE (barcode IS NOT NULL);
CREATE INDEX idx_products_category ON public.products USING btree (category) WHERE (active = true);
CREATE INDEX idx_products_name_trgm ON public.products USING gin (name gin_trgm_ops);
CREATE INDEX idx_products_sku ON public.products USING btree (sku) WHERE (active = true);
CREATE INDEX idx_qri_request ON public.quote_request_items USING btree (quote_request_id);
CREATE INDEX idx_qrs_queue ON public.quote_request_sends USING btree (queue_id);
CREATE INDEX idx_qrs_quote ON public.quote_request_sends USING btree (quote_request_id);
CREATE INDEX idx_qr_sent_suppliers ON public.quote_requests USING gin (sent_supplier_ids);
CREATE INDEX idx_qr_service_order ON public.quote_requests USING btree (service_order_id);
CREATE INDEX idx_qr_status ON public.quote_requests USING btree (status);
CREATE INDEX idx_qresp_request ON public.quote_responses USING btree (quote_request_id);
CREATE INDEX idx_qresp_supplier ON public.quote_responses USING btree (supplier_id);
CREATE INDEX idx_receivables_client_id ON public.receivables USING btree (client_id);
CREATE INDEX idx_receivables_client_status ON public.receivables USING btree (client_id, status);
CREATE INDEX idx_receivables_deposit ON public.receivables USING btree (service_order_id, is_deposit, status) WHERE (is_deposit = true);
CREATE INDEX idx_receivables_ifd ON public.receivables USING btree (issued_fiscal_document_id);
CREATE INDEX idx_receivables_reminder ON public.receivables USING btree (due_date, status, reminder_sent_at) WHERE (status = ANY (ARRAY['pending'::text, 'partially_paid'::text]));
CREATE UNIQUE INDEX receivables_uma_por_transacao ON public.receivables USING btree (bank_transaction_id) WHERE (bank_transaction_id IS NOT NULL);
CREATE INDEX idx_reconciliation_log_data ON public.reconciliation_log USING btree (ocorrido_em DESC);
CREATE INDEX idx_reconciliation_log_transacao ON public.reconciliation_log USING btree (bank_transaction_id) WHERE (bank_transaction_id IS NOT NULL);
CREATE INDEX idx_reconciliation_memory_key ON public.reconciliation_memory USING btree (statement_key);
CREATE UNIQUE INDEX reconciliation_memory_key_client ON public.reconciliation_memory USING btree (statement_key, client_id);
CREATE INDEX saved_filters_default_idx ON public.saved_filters USING btree (filter_type, user_id) WHERE (is_default = true);
CREATE UNIQUE INDEX saved_filters_one_default_per_type ON public.saved_filters USING btree (filter_type, COALESCE(user_id, '00000000-0000-0000-0000-000000000000'::uuid)) WHERE (is_default = true);
CREATE INDEX saved_filters_type_idx ON public.saved_filters USING btree (filter_type);
CREATE INDEX service_cases_lookup ON public.service_cases USING btree (service_id, usable, created_at DESC);
CREATE INDEX idx_service_order_parts_so_id ON public.service_order_parts USING btree (service_order_id);
CREATE INDEX so_parts_por_linha ON public.service_order_parts USING btree (service_order_service_id);
CREATE INDEX idx_so_photos_order ON public.service_order_photos USING btree (service_order_id);
CREATE INDEX idx_sos_fiscal_verb ON public.service_order_services USING btree (fiscal_verb) WHERE (fiscal_verb IS NOT NULL);
CREATE INDEX so_services_sistema ON public.service_order_services USING btree (service_system);
CREATE INDEX so_services_verbo ON public.service_order_services USING btree (service_verb);
CREATE INDEX idx_so_signatures_service_order ON public.service_order_signatures USING btree (service_order_id);
CREATE INDEX idx_so_signatures_signed_at ON public.service_order_signatures USING btree (signed_at DESC);
CREATE INDEX service_order_steps_assigned ON public.service_order_steps USING btree (assigned_user_id, status) WHERE (status = ANY (ARRAY['pending'::text, 'in_progress'::text]));
CREATE INDEX service_order_steps_os_seq ON public.service_order_steps USING btree (service_order_id, seq);
CREATE INDEX so_steps_block_key ON public.service_order_steps USING btree (service_order_id, block_key);
CREATE INDEX idx_service_orders_client_id ON public.service_orders USING btree (client_id);
CREATE INDEX idx_service_orders_client_status ON public.service_orders USING btree (client_id, status);
CREATE INDEX idx_service_orders_created_at ON public.service_orders USING btree (created_at DESC);
CREATE INDEX idx_service_orders_marina_id ON public.service_orders USING btree (marina_id);
CREATE INDEX idx_service_orders_share_token ON public.service_orders USING btree (share_token);
CREATE INDEX idx_service_orders_status ON public.service_orders USING btree (status);
CREATE INDEX idx_service_orders_vessel_id ON public.service_orders USING btree (vessel_id);
CREATE INDEX step_blocks_sistema ON public.service_step_blocks USING btree (applies_to_system, block_role, seq) WHERE active;
CREATE INDEX step_blocks_verbo ON public.service_step_blocks USING btree (applies_to_verb, seq) WHERE active;
CREATE INDEX service_step_templates_service ON public.service_step_templates USING btree (service_id, active, seq);
CREATE INDEX service_survey_answers_survey ON public.service_survey_answers USING btree (survey_id, seq);
CREATE INDEX service_survey_templates_service ON public.service_survey_templates USING btree (service_id, active, seq);
CREATE INDEX survey_tpl_por_eixo ON public.service_survey_templates USING btree (applies_to_system, applies_to_verb) WHERE active;
CREATE INDEX service_surveys_os ON public.service_surveys USING btree (service_order_id);
CREATE INDEX service_surveys_status ON public.service_surveys USING btree (status, created_at DESC);
CREATE INDEX idx_services_fiscal_verb ON public.services USING btree (fiscal_verb) WHERE (fiscal_verb IS NOT NULL);
CREATE INDEX services_classificacao ON public.services USING btree (service_verb, service_system) WHERE active;
CREATE INDEX suppliers_phone_key8 ON public.suppliers USING btree ("right"(regexp_replace(COALESCE(phone, ''::text), '\D'::text, ''::text, 'g'::text), 8));
CREATE INDEX idx_survey_material_rules_template ON public.survey_material_rules USING btree (template_id) WHERE active;
CREATE INDEX task_reminders_due ON public.task_reminders USING btree (remind_at) WHERE (sent_at IS NULL);
CREATE INDEX task_reminders_task ON public.task_reminders USING btree (task_id);
CREATE INDEX idx_time_entries_so_id ON public.time_entries USING btree (service_order_id);
CREATE INDEX time_entries_por_shift ON public.time_entries USING btree (shift_id) WHERE (shift_id IS NOT NULL);
CREATE INDEX time_entries_step ON public.time_entries USING btree (step_id);
CREATE INDEX idx_vessels_client_id ON public.vessels USING btree (client_id);
CREATE INDEX idx_vessels_marina_id ON public.vessels USING btree (marina_id);
CREATE INDEX idx_wa_leads_status ON public.whatsapp_leads USING btree (status, last_message_at DESC);
CREATE INDEX idx_whatsapp_leads_phone ON public.whatsapp_leads USING btree (phone_normalized);
CREATE INDEX idx_whatsapp_leads_status ON public.whatsapp_leads USING btree (status);
CREATE INDEX whatsapp_leads_status_last_inbound_idx ON public.whatsapp_leads USING btree (status, last_inbound_at DESC NULLS LAST);
CREATE INDEX whatsapp_leads_unread_idx ON public.whatsapp_leads USING btree (unread_count DESC) WHERE (unread_count > 0);
CREATE INDEX idx_wa_msgs_phone ON public.whatsapp_messages USING btree (phone_normalized, occurred_at DESC);
CREATE INDEX idx_wamsg_supplier ON public.whatsapp_messages USING btree (supplier_id) WHERE (supplier_id IS NOT NULL);
CREATE INDEX idx_whatsapp_messages_client ON public.whatsapp_messages USING btree (client_id);
CREATE INDEX idx_whatsapp_messages_lead ON public.whatsapp_messages USING btree (lead_id);
CREATE INDEX idx_whatsapp_messages_occurred ON public.whatsapp_messages USING btree (occurred_at DESC);
CREATE INDEX idx_whatsapp_messages_phone ON public.whatsapp_messages USING btree (phone_normalized);
CREATE INDEX whatsapp_messages_client_id_idx ON public.whatsapp_messages USING btree (client_id) WHERE (client_id IS NOT NULL);
CREATE INDEX whatsapp_messages_delivery_status_idx ON public.whatsapp_messages USING btree (delivery_status) WHERE (delivery_status = ANY (ARRAY['sent'::text, 'queued'::text, 'failed'::text]));
CREATE INDEX whatsapp_messages_direction_created_idx ON public.whatsapp_messages USING btree (direction, created_at DESC);
CREATE INDEX whatsapp_messages_lead_id_idx ON public.whatsapp_messages USING btree (lead_id) WHERE (lead_id IS NOT NULL);
CREATE INDEX whatsapp_messages_phone_created_idx ON public.whatsapp_messages USING btree (phone_normalized, created_at DESC);
CREATE UNIQUE INDEX whatsapp_messages_wa_message_id_unique ON public.whatsapp_messages USING btree (wa_message_id) WHERE (wa_message_id IS NOT NULL);
CREATE INDEX idx_wss_next_run ON public.whatsapp_scheduled_sends USING btree (next_run_at) WHERE (status = 'pending'::text);
CREATE INDEX idx_wss_rec ON public.whatsapp_scheduled_sends USING btree (receivable_id);
CREATE INDEX idx_wss_so ON public.whatsapp_scheduled_sends USING btree (service_order_id);
CREATE INDEX idx_wss_status ON public.whatsapp_scheduled_sends USING btree (status);
CREATE INDEX idx_wa_queue_pending ON public.whatsapp_send_queue USING btree (status, scheduled_for, priority) WHERE (status = 'pending'::text);
CREATE INDEX idx_wa_queue_phone ON public.whatsapp_send_queue USING btree (phone_normalized, created_at DESC);
CREATE INDEX idx_wa_queue_source ON public.whatsapp_send_queue USING btree (source, created_at DESC);
CREATE INDEX idx_wss_status_lookup ON public.whatsapp_status_scheduled USING btree (status);
CREATE INDEX idx_wss_status_pending ON public.whatsapp_status_scheduled USING btree (scheduled_at) WHERE (status = 'pending'::text);
CREATE UNIQUE INDEX work_profiles_um_vigente_por_payee ON public.work_profiles USING btree (payee_id) WHERE ((vigencia_fim IS NULL) AND (payee_id IS NOT NULL));
CREATE UNIQUE INDEX work_profiles_um_vigente_por_user ON public.work_profiles USING btree (app_user_id) WHERE ((vigencia_fim IS NULL) AND (app_user_id IS NOT NULL));
CREATE INDEX work_shifts_abertos ON public.work_shifts USING btree (work_profile_id) WHERE (fim IS NULL);
CREATE INDEX work_shifts_por_perfil_data ON public.work_shifts USING btree (work_profile_id, data DESC);
CREATE INDEX work_shifts_por_status ON public.work_shifts USING btree (status, data DESC);
CREATE INDEX work_shifts_service_order_idx ON public.work_shifts USING btree (service_order_id) WHERE (service_order_id IS NOT NULL);
