-- 07 · Triggers (public, auth e storage — os de auth/storage chamam funções do public)
-- Gerado por scripts/snapshot-producao.mjs a partir dos catálogos do banco de produção.
-- NÃO editar à mão: regenerar. A data e as contagens ficam no README.md ao lado.

CREATE TRIGGER update_agenda_tasks_updated_at BEFORE UPDATE ON agenda_tasks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER ai_agent_memory_updated_at BEFORE UPDATE ON ai_agent_memory FOR EACH ROW EXECUTE FUNCTION set_ai_agent_memory_updated_at();
CREATE TRIGGER ai_agent_tasks_updated_at BEFORE UPDATE ON ai_agent_tasks FOR EACH ROW EXECUTE FUNCTION set_ai_agent_tasks_updated_at();
CREATE TRIGGER ai_inbound_sessions_updated_at BEFORE UPDATE ON ai_inbound_sessions FOR EACH ROW EXECUTE FUNCTION set_ai_inbound_sessions_updated_at();
CREATE TRIGGER trg_ai_op_drafts_updated BEFORE UPDATE ON ai_operator_drafts FOR EACH ROW EXECUTE FUNCTION set_updated_at_now();
CREATE TRIGGER trg_ai_op_memory_updated BEFORE UPDATE ON ai_operator_memory_notes FOR EACH ROW EXECUTE FUNCTION set_updated_at_now();
CREATE TRIGGER trg_ai_op_pending_guard BEFORE UPDATE ON ai_operator_pending_actions FOR EACH ROW EXECUTE FUNCTION ai_op_protect_pending_action();
CREATE TRIGGER trg_ai_op_sessions_updated BEFORE UPDATE ON ai_operator_sessions FOR EACH ROW EXECUTE FUNCTION set_updated_at_now();
CREATE TRIGGER ai_workflows_updated_at BEFORE UPDATE ON ai_workflows FOR EACH ROW EXECUTE FUNCTION set_ai_workflows_updated_at();
CREATE TRIGGER update_app_settings_updated_at BEFORE UPDATE ON app_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_app_users_updated_at BEFORE UPDATE ON app_users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER bank_charges_updated_at BEFORE UPDATE ON bank_charges FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER bank_connections_updated_at BEFORE UPDATE ON bank_connections FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_client_whatsapp_settings_updated_at BEFORE UPDATE ON client_whatsapp_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_clients_updated_at BEFORE UPDATE ON clients FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER collections_updated_at BEFORE UPDATE ON collections FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_eql_updated BEFORE UPDATE ON external_quote_leads FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_eqp_updated BEFORE UPDATE ON external_quote_parts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_eqs_updated BEFORE UPDATE ON external_quote_services FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_eq_updated BEFORE UPDATE ON external_quotes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER finance_review_updated_at BEFORE UPDATE ON finance_review_queue FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER finance_rules_updated_at BEFORE UPDATE ON finance_rules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_touch_fed BEFORE UPDATE ON fiscal_emission_drafts FOR EACH ROW EXECUTE FUNCTION touch_fiscal_emission_draft();
CREATE TRIGGER sync_fiscal_note_items AFTER UPDATE ON fiscal_notes FOR EACH ROW EXECUTE FUNCTION trg_sync_fiscal_note_items();
CREATE TRIGGER update_fiscal_notes_updated_at BEFORE UPDATE ON fiscal_notes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_invoices_updated_at BEFORE UPDATE ON invoices FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_reverse_nfe_settlement_on_cancel BEFORE UPDATE ON issued_fiscal_documents FOR EACH ROW EXECUTE FUNCTION reverse_nfe_settlement_on_cancel();
CREATE TRIGGER update_marinas_updated_at BEFORE UPDATE ON marinas FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER payables_categoria_valida BEFORE INSERT OR UPDATE OF expense_category ON payables FOR EACH ROW EXECUTE FUNCTION valida_categoria_de_despesa();
CREATE TRIGGER trg_payables_periodo_fechado BEFORE INSERT ON payables FOR EACH ROW EXECUTE FUNCTION bloqueia_lancamento_em_periodo_fechado();
CREATE TRIGGER update_payables_updated_at BEFORE UPDATE ON payables FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER payees_updated_at BEFORE UPDATE ON payees FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_touch_payroll_lines BEFORE UPDATE ON payroll_lines FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_touch_payroll_periods BEFORE UPDATE ON payroll_periods FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER set_updated_at_product_categories BEFORE UPDATE ON product_categories FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER product_components_rollup AFTER INSERT OR DELETE OR UPDATE ON product_components FOR EACH ROW EXECUTE FUNCTION trg_product_components_rollup();
CREATE TRIGGER set_updated_at_product_suppliers BEFORE UPDATE ON product_suppliers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER tr_log_product_cost_change AFTER UPDATE OF cost_price ON products FOR EACH ROW EXECUTE FUNCTION log_product_cost_change();
CREATE TRIGGER trg_products_fiscal_complete BEFORE INSERT OR UPDATE OF ncm, cfop, csosn, fiscal_origin, use_global_fiscal ON products FOR EACH ROW EXECUTE FUNCTION compute_product_fiscal_complete();
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_poi_total AFTER INSERT OR DELETE OR UPDATE ON purchase_order_items FOR EACH ROW EXECUTE FUNCTION trg_poi_recalc_total();
CREATE TRIGGER trg_po_updated_at BEFORE UPDATE ON purchase_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_quote_requests_updated_at BEFORE UPDATE ON quote_requests FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_quote_responses_updated_at BEFORE UPDATE ON quote_responses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER on_quote_deposit_paid AFTER UPDATE ON receivables FOR EACH ROW EXECUTE FUNCTION handle_quote_deposit_payment();
CREATE TRIGGER receivables_coerencia BEFORE INSERT OR UPDATE OF amount, due_date, issue_date, due_on_completion, status ON receivables FOR EACH ROW EXECUTE FUNCTION valida_recebivel_coerente();
CREATE TRIGGER trg_receivables_periodo_fechado BEFORE INSERT ON receivables FOR EACH ROW EXECUTE FUNCTION bloqueia_lancamento_em_periodo_fechado();
CREATE TRIGGER trg_sync_collection_from_receivable AFTER UPDATE OF status ON receivables FOR EACH ROW EXECUTE FUNCTION sync_collection_from_receivable();
CREATE TRIGGER trg_sync_payment_status AFTER INSERT OR DELETE OR UPDATE OF status, paid_amount, amount, service_order_id ON receivables FOR EACH ROW EXECUTE FUNCTION sync_service_order_payment_status();
CREATE TRIGGER update_receivables_updated_at BEFORE UPDATE ON receivables FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER set_updated_at_service_cases BEFORE UPDATE ON service_cases FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER set_updated_at_service_fiscal_verbs BEFORE UPDATE ON service_fiscal_verbs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER set_updated_at_so_expenses BEFORE UPDATE ON service_order_expenses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER parts_reservation AFTER INSERT OR DELETE OR UPDATE ON service_order_parts FOR EACH ROW EXECUTE FUNCTION trg_parts_reservation();
CREATE TRIGGER trg_warranty_parts BEFORE INSERT OR UPDATE ON service_order_parts FOR EACH ROW EXECUTE FUNCTION calc_warranty_expiry();
CREATE TRIGGER update_service_order_parts_updated_at BEFORE UPDATE ON service_order_parts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER set_updated_at_service_order_services BEFORE UPDATE ON service_order_services FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_warranty_services BEFORE INSERT OR UPDATE ON service_order_services FOR EACH ROW EXECUTE FUNCTION calc_warranty_expiry();
CREATE TRIGGER set_updated_at_service_order_steps BEFORE UPDATE ON service_order_steps FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_log_step_time_entry AFTER UPDATE ON service_order_steps FOR EACH ROW EXECUTE FUNCTION log_step_time_entry();
CREATE TRIGGER trg_rollup_step_time AFTER INSERT OR DELETE OR UPDATE OF status, actual_minutes, started_at, completed_at ON service_order_steps FOR EACH ROW EXECUTE FUNCTION rollup_step_time_to_service_line();
CREATE TRIGGER update_service_order_technicians_updated_at BEFORE UPDATE ON service_order_technicians FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER so_status_stock AFTER UPDATE OF status ON service_orders FOR EACH ROW EXECUTE FUNCTION trg_so_status_stock();
CREATE TRIGGER trg_ai_so_lifecycle AFTER UPDATE OF status ON service_orders FOR EACH ROW EXECUTE FUNCTION private.ai_so_status_change_hook();
CREATE TRIGGER trg_create_service_cases AFTER UPDATE ON service_orders FOR EACH ROW EXECUTE FUNCTION create_service_cases_on_complete();
CREATE TRIGGER trg_detect_so_change_after_signature BEFORE UPDATE ON service_orders FOR EACH ROW EXECUTE FUNCTION detect_so_change_after_signature();
CREATE TRIGGER trg_sync_balance_due_on_completion AFTER UPDATE ON service_orders FOR EACH ROW WHEN (new.status = 'completed'::text AND old.status IS DISTINCT FROM 'completed'::text) EXECUTE FUNCTION sync_balance_due_on_completion();
CREATE TRIGGER trg_sync_commission_on_complete AFTER UPDATE OF status ON service_orders FOR EACH ROW EXECUTE FUNCTION sync_commission_on_so_complete();
CREATE TRIGGER update_service_orders_updated_at BEFORE UPDATE ON service_orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER set_updated_at_service_step_blocks BEFORE UPDATE ON service_step_blocks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER set_updated_at_service_step_templates BEFORE UPDATE ON service_step_templates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER set_updated_at_service_survey_templates BEFORE UPDATE ON service_survey_templates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER set_updated_at_service_surveys BEFORE UPDATE ON service_surveys FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER set_updated_at_service_systems BEFORE UPDATE ON service_systems FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER set_updated_at_service_verbs BEFORE UPDATE ON service_verbs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER set_updated_at_services BEFORE UPDATE ON services FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER set_updated_at_suppliers BEFORE UPDATE ON suppliers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_time_entries_updated_at BEFORE UPDATE ON time_entries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_vessels_updated_at BEFORE UPDATE ON vessels FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_whatsapp_leads_updated_at BEFORE UPDATE ON whatsapp_leads FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_whatsapp_read_state_updated BEFORE UPDATE ON whatsapp_read_state FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wss_updated_at BEFORE UPDATE ON whatsapp_scheduled_sends FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_wa_queue_updated_at BEFORE UPDATE ON whatsapp_send_queue FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_whatsapp_status_scheduled_updated_at BEFORE UPDATE ON whatsapp_status_scheduled FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_whatsapp_templates_updated BEFORE UPDATE ON whatsapp_templates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_touch_work_profiles BEFORE UPDATE ON work_profiles FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_calc_shift_duration BEFORE INSERT OR UPDATE ON work_shifts FOR EACH ROW EXECUTE FUNCTION calc_shift_duration();
CREATE TRIGGER enforce_bucket_name_length_trigger BEFORE INSERT OR UPDATE OF name ON storage.buckets FOR EACH ROW EXECUTE FUNCTION storage.enforce_bucket_name_length();
CREATE TRIGGER protect_buckets_delete BEFORE DELETE ON storage.buckets FOR EACH STATEMENT EXECUTE FUNCTION storage.protect_delete();
CREATE TRIGGER protect_objects_delete BEFORE DELETE ON storage.objects FOR EACH STATEMENT EXECUTE FUNCTION storage.protect_delete();
CREATE TRIGGER update_objects_updated_at BEFORE UPDATE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.update_updated_at_column();
