-- 09 · Privilégios de tabela/view para anon, authenticated e service_role
-- Gerado por scripts/snapshot-producao.mjs a partir dos catálogos do banco de produção.
-- NÃO editar à mão: regenerar. A data e as contagens ficam no README.md ao lado.

GRANT DELETE, INSERT, SELECT, UPDATE ON public.agenda_detector_exclusions TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.agenda_detector_exclusions TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.agenda_detector_exclusions TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.agenda_suggestions TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.agenda_suggestions TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.agenda_suggestions TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.agenda_tasks TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.agenda_tasks TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.agenda_tasks TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_agent_memory TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_agent_memory TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_agent_memory TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_agent_tasks TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_agent_tasks TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_agent_tasks TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_business_alerts TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_business_alerts TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_business_alerts TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_comms_log TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_comms_log TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_comms_log TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_correction_patterns TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_correction_patterns TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_correction_patterns TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_daily_briefings TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_daily_briefings TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_daily_briefings TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_inbound_sessions TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_inbound_sessions TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_inbound_sessions TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_learned_routines TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_learned_routines TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_learned_routines TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_lifecycle_events TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_lifecycle_events TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_lifecycle_events TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_message_feedback TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_message_feedback TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_message_feedback TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_alerts_log TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_alerts_log TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_operator_alerts_log TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_audit TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_audit TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_operator_audit TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_channel_events TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_channel_events TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_operator_channel_events TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_draft_items TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_draft_items TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_operator_draft_items TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_drafts TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_drafts TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_operator_drafts TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_memory_notes TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_memory_notes TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_operator_memory_notes TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_messages TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_messages TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_operator_messages TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_pending_actions TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_pending_actions TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_operator_pending_actions TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_sessions TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_operator_sessions TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_operator_sessions TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_suggestion_reviews TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_suggestion_reviews TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_workflows TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.ai_workflows TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.ai_workflows TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.api_references TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.api_references TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.api_references TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.app_error_logs TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.app_error_logs TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.app_error_logs TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.app_notifications TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.app_notifications TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.app_notifications TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.app_settings TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.app_settings TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.app_settings TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.app_users TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.app_users TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.app_users TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.audit_log TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.audit_log TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.audit_log TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.bank_balance_checks TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.bank_balance_checks TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.bank_charges TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.bank_charges TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.bank_charges TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.bank_connections TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.bank_connections TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.bank_connections TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.bank_transactions TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.bank_transactions TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.bank_transactions TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.bank_transactions_situacao TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.bank_transactions_situacao TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.card_installment_fees TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.card_installment_fees TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.card_installment_fees TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.client_whatsapp_settings TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.client_whatsapp_settings TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.client_whatsapp_settings TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.clients TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.clients TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.clients TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.collection_contacts TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.collection_contacts TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.collection_contacts TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.collection_templates TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.collection_templates TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.collection_templates TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.collections TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.collections TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.collections TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.commissions TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.commissions TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.commissions TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.company_fiscal_settings TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.company_fiscal_settings TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.conciliacao_lancamentos TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.conciliacao_lancamentos TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.cost_centers TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.cost_centers TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.cost_centers TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.dc_ampacity_ratings TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.dc_ampacity_ratings TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.entity_open_loops TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.entity_open_loops TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.entity_open_loops TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.erp_open_loop_facts TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.erp_open_loop_facts TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.exchange_rates TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.exchange_rates TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.exchange_rates TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.external_quote_leads TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.external_quote_leads TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.external_quote_leads TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.external_quote_parts TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.external_quote_parts TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.external_quote_parts TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.external_quote_services TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.external_quote_services TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.external_quote_services TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.external_quotes TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.external_quotes TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.external_quotes TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.extrato_a_tratar TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.extrato_a_tratar TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.faturas_do_cartao TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.faturas_do_cartao TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.finance_review_queue TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.finance_review_queue TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.finance_review_queue TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.finance_rules TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.finance_rules TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.finance_rules TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.financial_categories TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.financial_categories TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.financial_categories TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.fiscal_document_sequences TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.fiscal_document_sequences TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.fiscal_document_sequences TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.fiscal_emission_drafts TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.fiscal_emission_drafts TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.fiscal_emission_drafts TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.fiscal_note_items TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.fiscal_note_items TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.fiscal_note_items TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.fiscal_notes TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.fiscal_notes TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.fiscal_notes TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.import_sessions TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.import_sessions TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.import_sessions TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.inventory_movements TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.inventory_movements TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.inventory_movements TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.invoices TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.invoices TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.invoices TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.issued_fiscal_documents TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.issued_fiscal_documents TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.issued_fiscal_documents TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.maintenance_plans TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.maintenance_plans TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.maintenance_plans TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.marinas TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.marinas TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.marinas TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.payables TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.payables TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.payables TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.payees TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.payees TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.payment_condition_presets TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.payment_condition_presets TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.payment_condition_presets TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.payments TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.payments TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.payments TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.payroll_lines TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.payroll_lines TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.payroll_periods TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.payroll_periods TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.periodos_fechados TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.periodos_fechados TO service_role;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.pluggy_amostra_payload TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.price_update_suggestions TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.price_update_suggestions TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.price_update_suggestions TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.product_aliases TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.product_aliases TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.product_aliases TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.product_availability TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.product_availability TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.product_availability TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.product_categories TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.product_categories TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.product_categories TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.product_components TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.product_components TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.product_components TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.product_price_history TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.product_price_history TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.product_price_history TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.product_suppliers TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.product_suppliers TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.product_suppliers TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.products TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.products TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.products TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.products_stock_backup_pre_v2 TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.products_stock_backup_pre_v2 TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.products_stock_backup_pre_v2 TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.purchase_order_items TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.purchase_order_items TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.purchase_orders TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.purchase_orders TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.push_subscriptions TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.push_subscriptions TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.push_subscriptions TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.quote_request_items TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.quote_request_items TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.quote_request_sends TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.quote_request_sends TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.quote_requests TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.quote_requests TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.quote_responses TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.quote_responses TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.receivables TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.receivables TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.receivables TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.reconciliation_log TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.reconciliation_log TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.reconciliation_memory TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.reconciliation_memory TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.reconciliation_memory TO service_role;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.reparo_coremma_20260805 TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saved_filters TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.saved_filters TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.saved_filters TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_cases TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_cases TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_fiscal_verbs TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_fiscal_verbs TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_expenses TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_expenses TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_order_expenses TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_parts TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_parts TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_order_parts TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_parts_tecnico TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_order_parts_tecnico TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_photos TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_photos TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_order_photos TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_services TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_services TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_order_services TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_services_tecnico TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_order_services_tecnico TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_signatures TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_signatures TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_order_signatures TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_steps TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_order_steps TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_technicians TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_order_technicians TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_order_technicians TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_orders TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_orders TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_orders TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_orders_tecnico TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_orders_tecnico TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_step_blocks TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_step_blocks TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_step_blocks TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_step_templates TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_step_templates TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_survey_answers TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_survey_answers TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_survey_answers TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_survey_templates TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_survey_templates TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_survey_templates TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_surveys TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_surveys TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_surveys TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_systems TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_systems TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_systems TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_verbs TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.service_verbs TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.service_verbs TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.services TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.services TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.supplier_product_mappings TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.supplier_product_mappings TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.supplier_product_mappings TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.suppliers TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.suppliers TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.suppliers TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.survey_material_rules TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.survey_material_rules TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.task_reminders TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.task_reminders TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.task_reminders TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.time_entries TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.time_entries TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.time_entries TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.unidentified_contacts TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.unidentified_contacts TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.v_ai_custo_diario TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.v_ai_custo_diario TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.v_custo_real_mao_de_obra_por_os TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.v_custo_real_mao_de_obra_por_os TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.v_estoque_entradas_pendentes TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.v_estoque_entradas_pendentes TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.v_estoque_variancia TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.v_estoque_variancia TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.v_service_order_labor_variance TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.v_service_order_labor_variance TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.v_service_order_margin TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.v_service_order_margin TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.v_service_systems_status TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.v_service_systems_status TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.v_service_verbs_status TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.v_service_verbs_status TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.v_services_fiscal_efetivo TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.v_services_fiscal_efetivo TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.vessel_contacts TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.vessel_contacts TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.vessel_contacts TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.vessels TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.vessels TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.vessels TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.vw_os_profitability TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.vw_os_profitability TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.vw_os_profitability TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_blocked_numbers TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_blocked_numbers TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatsapp_blocked_numbers TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_conversation_assignments TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_conversation_assignments TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatsapp_conversation_assignments TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_leads TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_leads TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatsapp_leads TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_messages TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_messages TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatsapp_messages TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_quick_replies TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_quick_replies TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatsapp_quick_replies TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_read_state TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_read_state TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatsapp_read_state TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_scheduled_sends TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_scheduled_sends TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatsapp_scheduled_sends TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_send_queue TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_send_queue TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatsapp_send_queue TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_status_scheduled TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_status_scheduled TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatsapp_status_scheduled TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_templates TO anon;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.whatsapp_templates TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.whatsapp_templates TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.work_profiles TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.work_profiles TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.work_shifts TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.work_shifts TO service_role;
GRANT DELETE, INSERT, SELECT, UPDATE ON public.work_stop_reasons TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.work_stop_reasons TO service_role;
